### ISSUE TITLE
SDMXStructure.xsd - typo <xs:unique name="UniqueMetaataProviderScheme">

### ISSUE THREAD

**Issue by glennmdt** [glennmdt/sdmx-ml#58] opened 2021-06-22 07:59 UTC
Reference: https://github.com/sdmx3mdt/public-consultation/issues/16

**Comment by jgager** [comment] 2021-08-13 20:17
duplicate of 39 (which was pushed last round)

**Closed by jgager** 2021-08-13 20:17 UTC
Labels: bug, public consultation
